apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kyc-dev
resources:
  - ../../base/
labels:
  - pairs:
      app.kubernetes.io/name: kyc-service
      app.kubernetes.io/env: dev
      app.kubernetes.io/region: georgia
    includeSelectors: true