apiVersion: v1
kind: Service
metadata:
  name: kyc-service
  labels:
    app: kyc-service
spec:
  selector:
    app: kyc-service
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP