apiVersion: v1
kind: Service
metadata:
  name: kyc-service
  namespace: kyc-dev
spec:
  selector:
    app.kubernetes.io/name: kyc-service
    app.kubernetes.io/env: dev
    app.kubernetes.io/region: georgia
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP