apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyc-service-dev-georgia
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/fintech-devops
    targetRevision: HEAD
    path: k8s-manifests/georgia/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: kyc-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data